global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'auth-service'
  #   static_configs:
  #     - targets: ['auth-service:9101']
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       replacement: 'auth-service'
  #     - source_labels: [__address__]
  #       target_label: service
  #       replacement: 'auth-service'

  # - job_name: 'user-service'
  #   static_configs:
  #     - targets: ['user-service:9102']
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       replacement: 'user-service'
  #     - source_labels: [__address__]
  #       target_label: service
  #       replacement: 'user-service'

  # - job_name: 'payment-service'
  #   static_configs:
  #     - targets: ['payment-service:9103']
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       replacement: 'payment-service'
  #     - source_labels: [__address__]
  #       target_label: service
  #       replacement: 'payment-service'